/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type FeatureSection = {
  _type: "feature-section";
  options?: ModuleOptions;
  pretitle?: string;
  title?: string;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "heading-1"
          | "heading-2"
          | "heading-3"
          | "heading-4"
          | "heading-5"
          | "heading-6"
          | "body-1"
          | "body-2"
          | "body-3"
          | "body-4"
          | "body-5";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | ({
              _key: string;
            } & Link)
          | ({
              _key: string;
            } & SimplerColor)
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        loading?: "lazy" | "eager";
        caption?: string;
        source?: string;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & Code)
    | ({
        _key: string;
      } & CustomHtml)
  >;
  features?: Array<
    {
      _key: string;
    } & Feature
  >;
  ctas?: Array<
    {
      _key: string;
    } & Cta
  >;
  overlayOpacity?: number;
  assets?: Array<
    {
      _key: string;
    } & Img
  >;
};

export type RichtextModule = {
  _type: "richtext-module";
  options?: ModuleOptions;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "heading-1"
          | "heading-2"
          | "heading-3"
          | "heading-4"
          | "heading-5"
          | "heading-6"
          | "body-1"
          | "body-2"
          | "body-3"
          | "body-4"
          | "body-5";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | ({
              _key: string;
            } & Link)
          | ({
              _key: string;
            } & SimplerColor)
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        loading?: "lazy" | "eager";
        caption?: string;
        source?: string;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & Code)
    | ({
        _key: string;
      } & CustomHtml)
  >;
  tableOfContents?: boolean;
  tocPosition?: "left" | "right";
  stretch?: boolean;
};

export type SearchModule = {
  _type: "search-module";
  pretitle?: string;
  intro?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "heading-1"
          | "heading-2"
          | "heading-3"
          | "heading-4"
          | "heading-5"
          | "heading-6"
          | "body-1"
          | "body-2"
          | "body-3"
          | "body-4"
          | "body-5";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | ({
              _key: string;
            } & Link)
          | ({
              _key: string;
            } & SimplerColor)
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        loading?: "lazy" | "eager";
        caption?: string;
        source?: string;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & Code)
    | ({
        _key: string;
      } & CustomHtml)
  >;
  ctas?: Array<
    {
      _key: string;
    } & Cta
  >;
  scope?: "all" | "pages" | "path";
  path?: string;
};

export type HeroSplit = {
  _type: "hero.split";
  pretitle?: string;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "heading-1"
          | "heading-2"
          | "heading-3"
          | "heading-4"
          | "heading-5"
          | "heading-6"
          | "body-1"
          | "body-2"
          | "body-3"
          | "body-4"
          | "body-5";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | ({
              _key: string;
            } & Link)
          | ({
              _key: string;
            } & SimplerColor)
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        loading?: "lazy" | "eager";
        caption?: string;
        source?: string;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & Code)
    | ({
        _key: string;
      } & CustomHtml)
  >;
  ctas?: Array<
    {
      _key: string;
    } & Cta
  >;
  assets?: Array<
    | ({
        _key: string;
      } & Img)
    | ({
        _key: string;
      } & Code)
    | ({
        _key: string;
      } & CustomHtml)
  >;
  assetOnRight?: boolean;
  assetBelowContent?: boolean;
};

export type Hero = {
  _type: "hero";
  options?: ModuleOptions;
  pretitle?: string;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "heading-1"
          | "heading-2"
          | "heading-3"
          | "heading-4"
          | "heading-5"
          | "heading-6"
          | "body-1"
          | "body-2"
          | "body-3"
          | "body-4"
          | "body-5";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | ({
              _key: string;
            } & Link)
          | ({
              _key: string;
            } & SimplerColor)
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        loading?: "lazy" | "eager";
        caption?: string;
        source?: string;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & Code)
    | ({
        _key: string;
      } & CustomHtml)
  >;
  ctas?: Array<
    {
      _key: string;
    } & Cta
  >;
  assets?: Array<
    {
      _key: string;
    } & Img
  >;
  textAlign?: string;
  alignItems?: string;
};

export type CustomHtml = {
  _type: "custom-html";
  options?: ModuleOptions;
  className?: string;
  html?: Code;
  css?: Code;
};

export type CardList = {
  _type: "card-list";
  options?: ModuleOptions;
  pretitle?: string;
  intro?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "heading-1"
          | "heading-2"
          | "heading-3"
          | "heading-4"
          | "heading-5"
          | "heading-6"
          | "body-1"
          | "body-2"
          | "body-3"
          | "body-4"
          | "body-5";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | ({
              _key: string;
            } & Link)
          | ({
              _key: string;
            } & SimplerColor)
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        loading?: "lazy" | "eager";
        caption?: string;
        source?: string;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & Code)
    | ({
        _key: string;
      } & CustomHtml)
  >;
  ctas?: Array<
    {
      _key: string;
    } & Cta
  >;
  cards?: Array<{
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    content?: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "normal"
            | "heading-1"
            | "heading-2"
            | "heading-3"
            | "heading-4"
            | "heading-5"
            | "heading-6"
            | "body-1"
            | "body-2"
            | "body-3"
            | "body-4"
            | "body-5";
          listItem?: "bullet" | "number";
          markDefs?: Array<
            | ({
                _key: string;
              } & Link)
            | ({
                _key: string;
              } & SimplerColor)
          >;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          loading?: "lazy" | "eager";
          caption?: string;
          source?: string;
          _type: "image";
          _key: string;
        }
      | ({
          _key: string;
        } & Code)
      | ({
          _key: string;
        } & CustomHtml)
    >;
    ctas?: Array<
      {
        _key: string;
      } & Cta
    >;
    _type: "card";
    _key: string;
  }>;
  layout?: "grid" | "carousel";
  columns?: number;
  visualSeparation?: boolean;
};

export type Feature = {
  _type: "feature";
  name?: string;
  description?: string;
  icon?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?:
        | "normal"
        | "heading-1"
        | "heading-2"
        | "heading-3"
        | "heading-4"
        | "heading-5"
        | "heading-6"
        | "body-1"
        | "body-2"
        | "body-3"
        | "body-4"
        | "body-5";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        | ({
            _key: string;
          } & Link)
        | ({
            _key: string;
          } & SimplerColor)
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      loading?: "lazy" | "eager";
      caption?: string;
      source?: string;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & Code)
  | ({
      _key: string;
    } & CustomHtml)
>;

export type ModuleOptions = {
  _type: "module-options";
  hidden?: boolean;
  uid?: string;
};

export type Logo = {
  _type: "logo";
  name?: string;
  image?: {
    default?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    light?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    dark?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type LinkList = {
  _type: "link.list";
  link?: Link;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type Img = {
  _type: "img";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  responsive?: Array<{
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    media?: string;
    _type: "responsive";
    _key: string;
  }>;
  alt?: string;
  loading?: "lazy" | "eager";
};

export type Icon = {
  _type: "icon";
  ic0n?: string;
  size?: string;
};

export type Cta = {
  _type: "cta";
  link?: Link;
  style?: "primary" | "secondary" | "accent" | "outline" | "ghost" | "link";
};

export type Redirect = {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  source?: string;
  destination?: Link;
  permanent?: boolean;
};

export type Link = {
  _type: "link";
  label?: string;
  type?: "internal" | "external";
  internal?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  };
  external?: string;
  params?: string;
};

export type GlobalModule = {
  _id: string;
  _type: "global-module";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  path?: string;
  excludePaths?: Array<string>;
  before?: Array<
    | ({
        _key: string;
      } & CardList)
    | ({
        _key: string;
      } & CustomHtml)
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & HeroSplit)
    | ({
        _key: string;
      } & RichtextModule)
    | ({
        _key: string;
      } & SearchModule)
    | ({
        _key: string;
      } & FeatureSection)
  >;
  after?: Array<
    | ({
        _key: string;
      } & CardList)
    | ({
        _key: string;
      } & CustomHtml)
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & HeroSplit)
    | ({
        _key: string;
      } & RichtextModule)
    | ({
        _key: string;
      } & SearchModule)
    | ({
        _key: string;
      } & FeatureSection)
  >;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  modules?: Array<
    | ({
        _key: string;
      } & CardList)
    | ({
        _key: string;
      } & CustomHtml)
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & HeroSplit)
    | ({
        _key: string;
      } & RichtextModule)
    | ({
        _key: string;
      } & SearchModule)
    | ({
        _key: string;
      } & FeatureSection)
  >;
  metadata?: Metadata;
  language?: string;
};

export type Metadata = {
  _type: "metadata";
  slug?: Slug;
  title?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  info?: RichText;
  social?: Array<
    {
      _key: string;
    } & Link
  >;
  navigation?: Array<{
    links?: Array<
      {
        _key: string;
      } & Link
    >;
    _type: "menu";
    _key: string;
  }>;
  copyright?: RichText;
  importantLinks?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type Header = {
  _id: string;
  _type: "header";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  menu?: Array<
    | ({
        _key: string;
      } & Link)
    | ({
        _key: string;
      } & LinkList)
  >;
  ctas?: Array<
    {
      _key: string;
    } & Cta
  >;
};

export type Site = {
  _id: string;
  _type: "site";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seo?: {
    title?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type HighlightColor = {
  _type: "highlightColor";
  label?: string;
  value?: string;
};

export type TextColor = {
  _type: "textColor";
  label?: string;
  value?: string;
};

export type SimplerColor = {
  _type: "simplerColor";
  label?: string;
  value?: string;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | FeatureSection
  | RichtextModule
  | SearchModule
  | HeroSplit
  | Hero
  | CustomHtml
  | CardList
  | Feature
  | RichText
  | ModuleOptions
  | Logo
  | LinkList
  | Img
  | Icon
  | Cta
  | Redirect
  | Link
  | GlobalModule
  | Page
  | Metadata
  | Footer
  | Header
  | Site
  | HighlightColor
  | TextColor
  | SimplerColor
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
